# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementReportsRepo',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('er_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('er_enhancement_report', models.BinaryField(blank=True, null=True)),
                ('er_customer_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomerProgram')),
            ],
        ),
        migrations.CreateModel(
            name='SharedReportsRelation',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UpgridBaseUser')),
            ],
        ),
        migrations.CreateModel(
            name='WhoopsReportsRepo',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wr_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('wr_whoops_report', models.BinaryField(blank=True, null=True)),
                ('wr_customer_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomerProgram')),
                ('wr_share_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upgrid.SharedReportsRelation')),
            ],
        ),
        migrations.AddField(
            model_name='enhancementreportsrepo',
            name='er_share_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upgrid.SharedReportsRelation'),
        ),
    ]
