# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 03:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0002_auto_20161118_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedUpdateEmailQueue',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_report_type', models.CharField(blank=True, choices=[('whoops', 'Whoops'), ('enhancement', 'Enhancement')], max_length=20, null=True)),
                ('confirmed_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomerProgram')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='EnhancementUpdate',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('existing_report', models.BinaryField(blank=True, null=True)),
                ('cache_report', models.BinaryField(blank=True, null=True)),
                ('initial_diff', models.BinaryField(blank=True, null=True)),
                ('confirmed_diff', models.BinaryField(blank=True, null=True)),
                ('update_diff', models.BinaryField(blank=True, null=True)),
                ('most_recent', models.BooleanField(default=False)),
                ('last_edit_time', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomer')),
                ('customer_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomerProgram')),
            ],
        ),
        migrations.CreateModel(
            name='WhoopsUpdate',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('existing_report', models.BinaryField(blank=True, null=True)),
                ('cache_report', models.BinaryField(blank=True, null=True)),
                ('initial_diff', models.BinaryField(blank=True, null=True)),
                ('confirmed_diff', models.BinaryField(blank=True, null=True)),
                ('update_diff', models.BinaryField(blank=True, null=True)),
                ('most_recent', models.BooleanField(default=False)),
                ('last_edit_time', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomer')),
                ('customer_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomerProgram')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='whoopsupdate',
            unique_together=set([('customer', 'customer_program', 'created')]),
        ),
        migrations.AlterUniqueTogether(
            name='enhancementupdate',
            unique_together=set([('customer', 'customer_program', 'created')]),
        ),
    ]
