# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0003_auto_20170214_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycustomerprogram',
            name='enhancement_final_release_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='universitycustomerprogram',
            name='whoops_final_release_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='enhancementupdate',
            name='last_edit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='whoopsupdate',
            name='last_edit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
