# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0005_auto_20170426_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycustomer',
            name='can_ccemail',
            field=models.BooleanField(default=False),
        ),
    ]
