# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0007_upgridaccountmanager_modify_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycustomer',
            name='position_level',
            field=models.CharField(choices=[('university', 'University'), ('School', 'School'), ('acd_dep', 'Academic_Department'), ('admin_dep', 'Administrative_Department'), ('program', 'Program')], default='University', max_length=20, null=True),
        ),
    ]
