# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 14:17
from __future__ import unicode_literals

import apps.upgrid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0009_auto_20170519_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedreportsrelation',
            name='expired_time',
            field=models.DateTimeField(blank=True, default=apps.upgrid.models.one_day_hence),
        ),
    ]
