# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upgrid', '0010_sharedreportsrelation_expired_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeature',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view_only'),
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFeatureMapping',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomer')),
                ('feature', models.ManyToManyField(to='upgrid.CustomerFeature')),
            ],
        ),
        migrations.AlterField(
            model_name='upgridbaseuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
