# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0012_auto_20170615_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfeaturemapping',
            options={'default_permissions': ('add', 'change', 'delete', 'view_only'), 'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='customerfeature',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerfeature',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='customerfeaturemapping',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfeaturemapping',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerfeaturemapping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerfeaturemapping',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
