# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 15:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ceeb_program', '0030_auto_20170618_0609'),
        ('upgrid', '0014_auto_20170615_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDegreeReleaseReport',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceeb_program.UniversitySchool')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view_only'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='universitycustomer',
            name='non_degree_schools',
            field=models.ManyToManyField(blank=True, related_name='non_degree_user', to='ceeb_program.UniversitySchool'),
        ),
    ]
