# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 19:59
from __future__ import unicode_literals

import apps.upgrid.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0015_auto_20170630_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDegreeSharedReport',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expired_time', models.DateTimeField(blank=True, default=apps.upgrid.models.one_day_hence)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UpgridBaseUser')),
                ('reports', models.ManyToManyField(blank=True, null=True, to='upgrid.NonDegreeReport')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view_only'),
            },
        ),
    ]
