# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0015_auto_20170627_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nondegreereleasereport',
            old_name='report',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='universitycustomer',
            name='competing_schools',
            field=models.ManyToManyField(blank=True, related_name='_universitycustomer_competing_schools_+', to='ceeb_program.UniversitySchool'),
        ),
    ]
