# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0018_addnondegreewhoopsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='nondegreewhoopsreport',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nondegreewhoopsreport',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
