# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0019_auto_20170818_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDegreeReportCustomerMapping',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.UniversityCustomer')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upgrid.NonDegreeReport')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view_only'),
            },
        ),
    ]
