# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0020_nondegreereportcustomermapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nondegreereportcustomermapping',
            options={'default_permissions': ('add', 'change', 'delete', 'view_only')},
        ),
        migrations.RemoveField(
            model_name='nondegreereportcustomermapping',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nondegreereportcustomermapping',
            name='name',
        ),
    ]
