# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0021_auto_20170919_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='nondegreereportcustomermapping',
            name='send_fail',
            field=models.BooleanField(default=True),
        ),
    ]
