# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrid', '0022_nondegreereportcustomermapping_send_fail'),
    ]

    operations = [
        migrations.AddField(
            model_name='nondegreereportcustomermapping',
            name='email_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
