# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceeb_program', '0012_auto_20161031_0347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAssignment',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('InProgress', 'In progress'), ('NeedUpdate', 'Need update'), ('Done', 'Done')], default='Assigned', max_length=20, null=True, verbose_name='Assignment status')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceeb_program.Program')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view_only'),
            },
        ),
        migrations.CreateModel(
            name='ProgramProof',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('None', 'None'), ('Assigned', 'Assigned'), ('InProgress', 'In progress'), ('Done', 'Done')], default='None', max_length=20, null=True, verbose_name='Review status')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceeb_program.Program')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view_only'),
            },
        ),
    ]
